name: CI Prueba Básica

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al archivo
        run: chmod +x saludo.sh

      - name: Ejecutar saludo.sh
        run: ./saludo.sh
