name: CI Prueba Básica

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar que el workflow funciona
      run: echo "¡Pipeline ejecutado con éxito desde GitHub Actions!"
